name: bookspace
description: Application de réservation de salles

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.1.1
  fl_chart: ^1.2.0
  image_picker: ^0.8.7+4 
  file_picker: ^10.3.10
  google_fonts: ^8.0.2
  flutter_staggered_animations: ^1.1.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # Ajoute cette ligne

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" # Chemin vers ton image
  adaptive_icon_background: "#FFFFFF" # Couleur de fond (ex: blanc)
  adaptive_icon_foreground: "assets/icon/icon.png"